name: calebshirthum
description: "A new Flutter project."
publish_to: 'none' # Prevents accidental publishing to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  get: ^4.6.6
  google_fonts: ^6.2.1
  flutter_screenutil:
  pinput:
  flutter_faq: ^1.0.1+1
  font_awesome_flutter: ^10.7.0
  flutter_rating_bar:
  d_chart: ^2.6.9
  fl_chart:
  dotted_border: ^2.1.0
  percent_indicator: ^4.2.3
  google_maps_flutter: ^2.7.0
  loading_animation_widget: ^1.2.1
  image_picker: ^1.1.2
  zoom_pinch_overlay: ^1.4.3
  get_storage: ^2.1.1
  flutter_svg:
  qr_flutter:
  device_preview: ^1.2.0
  flutter_spinkit: ^5.2.1
  fluttertoast:
  flutter_html:
  geolocator: ^9.0.0
  geocoding:
  shimmer:
  flutter_launcher_icons: ^0.13.1
  cached_network_image: ^3.4.1
  change_app_package_name: ^1.4.0
  page_transition: ^2.1.0
  google_sign_in: ^6.2.2
  intl_phone_field: ^3.2.0
  url_launcher: ^6.3.1
  table_calendar: ^3.0.9
  socket_io_client:
  firebase_messaging: ^15.1.3
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.4
  action_slider: ^0.7.0
  smooth_page_indicator: ^1.2.1
  apple_maps_flutter:
  lottie: ^3.3.2
  permission_handler: ^11.3.0
  google_places_flutter: ^2.0.6
  flutter_dotenv: ^5.1.0
  file_picker: ^8.0.0
  mime_type: ^1.0.1
  mime: ^2.0.0
  http_parser: ^4.0.2
  sign_in_with_apple:
  flutter_local_notifications:





  gap: ^3.0.1
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png'"
  min_sdk_android: 21 # android min sdk min:16, default 21

flutter:
  uses-material-design: true

  # Add assets here
  assets:
    - assets/images/
    - assets/icon/
